// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.Models;

namespace Travel.Migrations
{
    [DbContext(typeof(TravelContext))]
    [Migration("20200128195512_SeedDateCity")]
    partial class SeedDateCity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Travel.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Rating");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            Name = "Tokyo",
                            Rating = 5
                        },
                        new
                        {
                            CityId = 2,
                            Name = "London",
                            Rating = 3
                        },
                        new
                        {
                            CityId = 3,
                            Name = "Kyoto",
                            Rating = 1
                        },
                        new
                        {
                            CityId = 4,
                            Name = "Taipei",
                            Rating = 5
                        },
                        new
                        {
                            CityId = 5,
                            Name = "Rio",
                            Rating = 3
                        });
                });

            modelBuilder.Entity("Travel.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Rating");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "Japan",
                            Rating = 5
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "England",
                            Rating = 5
                        },
                        new
                        {
                            CountryId = 3,
                            Name = "Japan",
                            Rating = 1
                        },
                        new
                        {
                            CountryId = 4,
                            Name = "Taiwan",
                            Rating = 5
                        },
                        new
                        {
                            CountryId = 5,
                            Name = "Brazil",
                            Rating = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
