// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.Models;

namespace Travel.Migrations
{
    [DbContext(typeof(TravelContext))]
    [Migration("20200128233051_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Travel.Models.Place", b =>
                {
                    b.Property<int>("PlaceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.HasKey("PlaceId");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            PlaceId = 1,
                            City = "Tokyo",
                            Country = "Japan"
                        },
                        new
                        {
                            PlaceId = 2,
                            City = "Seattle",
                            Country = "US"
                        },
                        new
                        {
                            PlaceId = 3,
                            City = "London",
                            Country = "England"
                        },
                        new
                        {
                            PlaceId = 4,
                            City = "Taipei",
                            Country = "Taiwan"
                        },
                        new
                        {
                            PlaceId = 5,
                            City = "Rio",
                            Country = "Brazil"
                        });
                });

            modelBuilder.Entity("Travel.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PlaceId");

                    b.Property<string>("individualReview");

                    b.HasKey("ReviewId");

                    b.HasIndex("PlaceId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            PlaceId = 1,
                            individualReview = "Great!"
                        },
                        new
                        {
                            ReviewId = 2,
                            PlaceId = 2,
                            individualReview = "I hated this place!"
                        },
                        new
                        {
                            ReviewId = 3,
                            PlaceId = 3,
                            individualReview = "Highly recommend!!"
                        },
                        new
                        {
                            ReviewId = 4,
                            PlaceId = 4,
                            individualReview = "I loved this place. I will come back!"
                        },
                        new
                        {
                            ReviewId = 5,
                            PlaceId = 5,
                            individualReview = "It was ok."
                        });
                });

            modelBuilder.Entity("Travel.Models.Review", b =>
                {
                    b.HasOne("Travel.Models.Place", "Place")
                        .WithMany("Reviews")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
