// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAPI.Models;

namespace Travel.Migrations
{
    [DbContext(typeof(TravelAPIContext))]
    partial class TravelAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelAPI.Models.Place", b =>
                {
                    b.Property<int>("PlaceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<double>("Rating");

                    b.HasKey("PlaceId");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            PlaceId = 1,
                            City = "Tokyo",
                            Country = "Japan",
                            Rating = 3.0
                        },
                        new
                        {
                            PlaceId = 2,
                            City = "Seattle",
                            Country = "US",
                            Rating = 4.0
                        },
                        new
                        {
                            PlaceId = 3,
                            City = "London",
                            Country = "England",
                            Rating = 3.5
                        },
                        new
                        {
                            PlaceId = 4,
                            City = "Taipei",
                            Country = "Taiwan",
                            Rating = 5.0
                        },
                        new
                        {
                            PlaceId = 5,
                            City = "Rio",
                            Country = "Brazil",
                            Rating = 0.0
                        });
                });

            modelBuilder.Entity("TravelAPI.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PlaceId");

                    b.Property<double>("Rating");

                    b.Property<string>("ReviewText");

                    b.Property<string>("UserName");

                    b.HasKey("ReviewId");

                    b.HasIndex("PlaceId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            PlaceId = 1,
                            Rating = 2.0,
                            ReviewText = "Great!",
                            UserName = "user1"
                        },
                        new
                        {
                            ReviewId = 2,
                            PlaceId = 2,
                            Rating = 1.0,
                            ReviewText = "I hated this place!",
                            UserName = "user2"
                        },
                        new
                        {
                            ReviewId = 3,
                            PlaceId = 3,
                            Rating = 4.5,
                            ReviewText = "Highly recommend!!",
                            UserName = "user1"
                        },
                        new
                        {
                            ReviewId = 4,
                            PlaceId = 4,
                            Rating = 5.0,
                            ReviewText = "I loved this place. I will come back!",
                            UserName = "user2"
                        },
                        new
                        {
                            ReviewId = 5,
                            PlaceId = 5,
                            Rating = 3.5,
                            ReviewText = "It was ok.",
                            UserName = "user2"
                        });
                });

            modelBuilder.Entity("TravelAPI.Models.Review", b =>
                {
                    b.HasOne("TravelAPI.Models.Place", "Place")
                        .WithMany("Reviews")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
